Change line numbers in documentation
collerek/ormar pull request #1265
Opened 2024-02-14 17:59 UTC by mekanix

I changed all occurrences of `Meta` that I knew how to, as well. Line numbers change when I replace `Meta` with `ormar_config`, so I did that. If you grep, you'll find more `Meta` instances around, but I don't know how to change them. For example, I never worked with signals, so I don't know how's that implemented now.

2024-02-14 18:08 UTC, mekanix commented
Do you want to teach me how new signals work, or you want to fill in that info yourself?

2024-02-18 19:14 UTC, collerek commented
@mekanix The signals are working like they used to, not sure what you refer to regarding Meta in there?

2024-02-18 23:38 UTC, mekanix commented
For example [here](https://github.com/mekanix/ormar/blob/line-numbers/docs/signals.md?plain=1#L109)

2024-02-19 09:15 UTC, collerek commented
Ah, ok, so you can assume what was in `Meta` will be now in `ormar_config`, it's registered [here](https://github.com/collerek/ormar/blob/2d798666c01a52012a1d6d754e5ae2b89acefb8f/ormar/models/metaclass.py#L121)

2024-02-19 13:29 UTC, mekanix commented
The only thing left is [this mention of Config](https://github.com/mekanix/ormar/blob/line-numbers/docs/models/index.md?plain=1#L320) that I don't know what to do with. Can you help, please?

2024-02-25 17:31 UTC, collerek requested changes
hi! In general looks good, great job! Some minor remarks (mostly related to missing table names in ormar_configs)

2024-02-25 17:31 UTC, collerek commented on docs/models/index.md
> +    ormar_config = base_ormar_config.copy(orders_by = ["-name"])
would add back explicit table name as this is one of the first section users read.

2024-02-25 17:31 UTC, collerek commented on docs/models/index.md
> +    ormar_config = base_ormar_config.copy(queryset_class=MyQuerySetClass)
table_name was set to `book` but in now books by default

2024-02-25 17:31 UTC, collerek commented on docs/fastapi/response.md
> +    ormar_config = base_ormar_config.copy()
Changed table name (default would be `categorys`)

2024-02-25 17:31 UTC, collerek commented on docs/fields/common-parameters.md
> +    ormar_config = base_ormar_config.copy()
Changed table name

2024-02-25 17:31 UTC, collerek commented on docs/fields/encryption.md
> +    ormar_config = base_ormar_config.copy()
changed table name

2024-02-25 17:31 UTC, collerek commented on docs/fields/field-types.md
> +    ormar_config = base_ormar_config.copy()
changed table name

2024-02-25 17:31 UTC, collerek commented on docs/models/inheritance.md
> +    ormar_config = base_ormar_config.copy()
Changed table name

2024-02-25 17:31 UTC, collerek commented on docs/models/inheritance.md
> +    ormar_config = base_ormar_config.copy()
changed table name

2024-02-25 17:31 UTC, collerek commented on docs/models/inheritance.md
> +    ormar_config = base_ormar_config.copy(tablename="busses2")
typo

2024-02-25 17:31 UTC, collerek commented on docs/models/inheritance.md
> +        exclude_parent_fields = ["updated_by", "updated_date"],
spaces around equal sign

2024-02-25 17:31 UTC, collerek commented on docs/queries/filter-and-sort.md
> +  * Model's `ormar_config` class `orders_by`
now it's not a class but an instance

2024-02-25 17:31 UTC, collerek commented on docs/queries/joins-and-subqueries.md
> +    ormar_config = base_ormar_config.copy()
changed table name

2024-02-25 17:31 UTC, collerek commented on docs/queries/joins-and-subqueries.md
> +    ormar_config = base_ormar_config.copy()
changed table name

2024-02-25 17:31 UTC, collerek commented on docs/transactions.md
> -
please restore it, just change Meta to ormar_config like everywhere else

2024-02-26 00:13 UTC, mekanix commented on README.md
> +base_ormar_config.metadata.create_all(engine)
What does it mean to run readme? Can I do it in the browser or you mean copy/paste the code and check it?

2024-02-26 08:22 UTC, collerek commented on README.md
> +base_ormar_config.metadata.create_all(engine)
Ah sorry, forgot to explain, there is a file `examples/script_from_readme.py` that should 1:1 match what is in the readme (might need changes, not sure if it was already updated in v2 pr). That one you could run and copy paste to readme after changes so they match. Unfortunately, github/pypi readme files do not support the embedding of code as we have in docs.

2024-03-04 09:29 UTC, mekanix commented on README.md
> +base_ormar_config.metadata.create_all(engine)
I totally missed this comment. I'll work on this and post and update in few days (sorry for not doing it sooner, I'm very busy this week).

2024-03-04 12:53 UTC, collerek commented on README.md
> +base_ormar_config.metadata.create_all(engine)
No worries, take your time I'm quite busy too. Note also other comments from the review about changed table names

2024-03-05 10:04 UTC, mekanix commented on README.md
> +base_ormar_config.metadata.create_all(engine)
I think everything is good now.

2024-03-05 11:22 UTC, collerek requested changes
There are still not addressed table name changes

2024-03-05 11:22 UTC, collerek commented on docs/fastapi/index.md
> +    ormar_config = base_ormar_config.copy()
missed changed name here

2024-03-05 11:22 UTC, collerek commented on docs/fields/encryption.md
> +    ormar_config = base_ormar_config.copy()
you didn't fix this, should be `ormar_config = base_ormar_config.copy(tablename="hashes")`

2024-03-05 11:23 UTC, collerek commented
Some of the old comments are not addressed too (also names changes)

2024-03-05 15:13 UTC, mekanix commented
My knee is killing me so my focus is bad. Sorry you have to go through the PR so many times. Well, get there :smile:

2024-03-10 13:24 UTC, collerek commented
Hi, do you know when you will be able to provide those few final changes?

2024-03-10 14:36 UTC, mekanix commented
I went through the `git show` and checked `tablename`. I caught few more and I squashed into one commit. My knee is hurt which means I have time, but the pain does steal the focus, so some errors might have sneaked in.

2024-03-10 15:18 UTC, collerek approved these changes

2024-03-10 15:18 UTC, merged