many-to-many nullable columns with through
collerek/ormar pull request #852
Opened 2022-09-27 01:44 UTC by nikelborm

such code:
```python
...
class TickerCollection(ormar.Model):
  class Meta(BaseMeta):
    tablename = "ticker_collection"

  id: int = ormar.Integer(name="ticker_collection_id", nullable=False, primary_key=True, autoincrement=True)

  createdByUser: Optional[User] = ormar.ForeignKey(User, name="created_by_user_id", nullable=True, unique=False)
  isPublic: bool                = ormar.Boolean(         name="is_public",          nullable=False, default=False)
  name: str                     = ormar.Text(            name="name",               nullable=False)
  description: str              = ormar.Text(            name="description",        nullable=True)
  tickers: Optional[List[Ticker]] = ormar.ManyToMany(
    to=Ticker,
    through=TickerToTickerCollection,
    related_name="tickerCollections",
    through_relation_name="ticker_collection_id",
    through_reverse_relation_name="ticker_id",
    # is_through_relation_column_nullable=False,
    # is_through_reverse_relation_column_nullable=False,
  )
...
```
cause such migration:
```python
...
op.create_table('ticker_to_ticker_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('ticker_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_collection_id'], ['ticker_collection.ticker_collection_id'], name='asd1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.ticker_id'], name='asd2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
...
```
Here `ticker_id` and `ticker_collection_id` are nullable by default, and there is no built-in way to set them non nullable.
I tried to set `sql_nullable` and `nullable` in arguments of `ormar.ManyToMany` but looks like it affects only typing information.
So then I added these two parameters, that will allow to override nullability of both `through` columns.

2022-12-10 16:26 UTC, collerek requested changes

2022-12-10 16:26 UTC, collerek commented on ormar/fields/many_to_many.py
> +    is_through_reverse_relation_column_nullable = kwargs.pop("is_through_reverse_relation_column_nullable", None)
Can you rename it to shorter names: `through_relation_nullable` and `through_reverse_relation_nullable`

2022-12-10 16:26 UTC, collerek commented on ormar/models/helpers/sqlalchemy.py
> +        model=model_field.owner, model_field=model_field, field_name=child_name, nullable=model_field.is_through_relation_column_nullable,
Can you add missing tests for setting that column settings nullable/ not nullable and different expected behavior?

2024-05-26 20:10 UTC, nikelborm commented
Hi @collerek
Since I wrote this PR, long time passed. At the time I wasn't much experienced in python\ormar and didn't have much time, so I wasn't able to properly write tests on this PR and fix your reviews, but now I hope I'm soon will be able to

2026-04-22 18:11 UTC, collerek approved these changes

2026-04-22 18:12 UTC, merged